config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  get :create_new, to: 'welcome#create_new'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout 'layouts/app_theme_frontend'

  before_action :authenticate_user!,  if: :needs_authenticate_user?
  before_action :authorize_action!,   if: :needs_authorize_action?

  def index; end
  def create_new; end

  private

  ################################################
  # Authorization
  ################################################

  def authorize_action!
    return if can_perform?
    authorization_exception!('Action is not allowed to perform')
  end

  ################################################
  # Do We Need to Perform a Callback?
  ################################################

  def needs_authenticate_user?
     except_actions = %w[index]
    !except_actions.include?(action_name)
  end

  def needs_authorize_action?
     except_actions = %w[index]
    !except_actions.include?(action_name)
  end
end

app/views/app_theme/layouts/app_theme_frontend.slim
- content_for :base_assets do
  = stylesheet_link_tag    'app_theme/frontend', media: :all, 'data-turbolinks-track' => true
  = javascript_include_tag 'app_theme/frontend', 'data-turbolinks-track' => true

doctype html

html.w100p.h100p
  head class=('log-js' if Rails.env.development?)
    meta charset='utf-8'
    title TheOpenCMS.org

    / = action_cable_meta_tag
    = csrf_meta_tags

  body.w100p.h100p.ffa
    .star_me_on_github
      = link_to 'https://github.com/TheOpenCMS/TheOpenCMS', target: :_blank do
        i.fa.fa-star>
        | me on
        i.fa.fa-github<

    .ptz_table.h100p.w100p
      .ptz_row
        = render template: 'app_theme/layouts/items/header'
      .ptz_row.h100p
        .w80p.ma
          .mt20.mb20
            = render partial: 'notifications/flash'
            = yield
      .ptz_row
        = render template: 'app_theme/layouts/items/footer'

  = yield(:base_assets)

  link(href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous")

  = render template: 'analytics/google.analytics', locals: { tracking_id: Settings.services.google_analytics.tracking_id }
  = render template: 'analytics/yandex.metrika',   locals: { tracking_id: Settings.services.yandex_metrika.tracking_id }

app/views/app_theme/layouts/items/footer.slim
.app_theme_layout-footer.posrel
  - if File.exist?(file = "#{ Rails.root}/public/release.txt")
    .app_theme_layout-footer-release_info.posabs.p10.fs11
      = File.open(file).read

  .app_theme_layout-footer-locale.posabs.p10.fs11
    = select nil, :locale, %w[ru en].map {|i| [i, i] }, { selected: session[:locale] }, class: 'js-select_locale'

  .tac.fs18.b.pt40
    | TheOpenCMS,
    =< Time.now.year

app/views/app_theme/layouts/items/header.slim
.app_theme_toolbar-block
  .ma.w80p.clearfix.fs15
    .pull-left
      span.mr5 = link_to 'theopencms.org', root_path, class: 'app_theme_toolbar-link'
      span.mr5 |
      span.mr5 = link_to 'Users', users_path, class: 'app_theme_toolbar-link'
      span.mr5 |
      span.mr5 = link_to 'Articles', articles_path, class: 'app_theme_toolbar-link'
      span.mr5 |
    - if current_user
      span.mr5 = link_to 'Create New', create_new_path, class: 'app_theme_toolbar-link'
      span.mr5 |
      span.mr5 = link_to 'My Profile', [:edit, @user], class: 'app_theme_toolbar-link'
      span.mr5 |
      span = link_to 'Logout', destroy_user_session_path, method: :delete, class: 'app_theme_toolbar-link'
    - else
      span= link_to 'Login', new_user_session_path, class: 'app_theme_toolbar-link'

.app_theme_layout-header
  .tac.mb20
    .mb20.fs30.pt40.ffg = link_to 'TheOpenCMS', 'https://github.com/TheOpenCMS/TheOpenCMS', target: :_blank
    .fs16.ffa.lh120 Modern, Engine-Based, Open Source CMS for Rails 5+

app/views/app_theme/layouts/layout.slim
- content_for :base_assets do
  = stylesheet_link_tag    'app_theme/frontend', media: :all, 'data-turbolinks-track' => true
  = javascript_include_tag 'app_theme/frontend', 'data-turbolinks-track' => true

doctype html

html.w100p.h100p
  head class=('log-js' if Rails.env.development?)
    meta charset='utf-8'
    title TheOpenCMS.org

    / = action_cable_meta_tag
    = csrf_meta_tags

  body.w100p.h100p.ffa
    .star_me_on_github
      = link_to 'https://github.com/TheOpenCMS/TheOpenCMS', target: :_blank do
        i.fa.fa-star>
        | me on
        i.fa.fa-github<

    .ptz_table.h100p.w100p
      .ptz_row
        = render template: 'app_theme/layouts/items/header'
      .ptz_row.h100p
        .w80p.ma
          .mt20.mb20
            = render partial: 'notifications/flash'
            = yield
      .ptz_row
        = render template: 'app_theme/layouts/items/footer'

  = yield(:base_assets)

  link(href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous")

  = render template: 'analytics/google.analytics', locals: { tracking_id: Settings.services.google_analytics.tracking_id }
  = render template: 'analytics/yandex.metrika',   locals: { tracking_id: Settings.services.yandex_metrika.tracking_id }

app/views/welcome/create_new.slim
- if can_perform?(scope: :article, acl: :shared, action: :new)
  = link_to t(:article, scope: [:welcome, :create_new]), new_article_path, class: 'ptz_btn ptz_size-20'

app/views/welcome/index.slim
h3.fs30.ffa.mb20 About the project

.fs18.lh130.mb30
  | This project is an open source initiative which was started by <a href='https://github.com/the-teacher' target='_blank'>Ilya N. Zykin</a>.
  =>
  | With this project I'm going to show some of my ideas about how a modern CMS may look.
  =>
  | This CMS has to be made of a couple of Rails Engines. Because Rails Engines is a great way to split a monolith Rails application into the parts and to make a code base better maintainable.

.fs18.lh130.mb30
  | I'm going to create some Rails Engines within this project. Each Rails Engine will provide a some part of a functionality.
  =>
  | The main idea of the project, after this project is finished anyone may reuse not only the main project, but also any separated part of the CMS.

.fs18.lh130.mb30
  | For example, it's make no sense to re-implement <u>User Profile</u> functionality for a new RoR project if we already have <a href='https://github.com/TheOpenCMS/user_room' target='_blank'>gem 'user_room'</a> from TheOpenCMS.
  =>
  | <a href='https://github.com/TheOpenCMS/user_room' target='_blank'>User Room</a> gem provides all typical actions for a user's profile. <u>Log In / Sign Up</u>, Log in via Social Networks, Uploading an avatar image, Cropping and so on.

.fs18.lh130.mb30
  | Also I've started this project, because I believe - <b>Content Is Everything!</b> That is why I'm going to create new one amazing CMS on Rails.

h3.fs30.ffa.mb20 Features

.fs18.lh120.mb30
  | This project out-of-the-box uses the following services, tools and technologies:

.tac.mb30
  .tos_feature.tos_feature-do
    | Digital Ocean

  .tos_feature.tos_feature-rails5
    | Rails 5.1.rc1+

  .tos_feature.tos_feature-psql
    | PostgreSQL

  .tos_feature.tos_feature-jquery
    | JQuery

  .tos_feature.tos_feature-bem
    | BEM

  .tos_feature.tos_feature-sass
    | SASS

  .tos_feature.tos_feature-turbolinks
    | TurboLinks

  .tos_feature.tos_feature-engines
    | Rails Engines

  .tos_feature.tos_feature-ujs
    | Rails Unobtrusive JS

  .tos_feature.tos_feature-sprockets
    | Rails Sprockets

  .tos_feature.tos_feature-redis
    | Redis

  .tos_feature.tos_feature-sidekiq
    | Sidekiq

  .tos_feature.tos_feature-puma
    | Puma

  .tos_feature.tos_feature-nginx
    | Nginx

  .tos_feature.tos_feature-rollbar
    | Rollbar

  .tos_feature.tos_feature-exception
    | Exception Notification

  .tos_feature.tos_feature-newrelic
    | New Relic

  .tos_feature.tos_feature-ga
    | Google Analytics

  .tos_feature.tos_feature-metrika
    | Yandex Metrika

  .tos_feature.tos_feature-letsencript
    | Let's Encript

.fs12.lh120.mb30.tar
  sup> *
  | All Names, Logos and Trademarks are used just for information purposes. All rights belongs to their respective owners.

h3.fs30.ffa.mb20 Current state of the Project

.fs18.lh130.mb30
  | Right now just an early release is available. The project is still under an active development. The project provides just simple functionality for a user's profile.
  =>
  | I still try to find optimal ways to provide a good decomposition of the project and ways to provide a good customization of the CMS.

.fs18.lh130.mb30
  | To be aware of the current state you can take a look at <a href='https://github.com/TheOpenCMS/TheOpenCMS/blob/master/docs/Changelog.md' target='_blank'>ChangeLog</a> and <a href='https://github.com/TheOpenCMS/TheOpenCMS/projects/1' target='_blank'>Project</a> pages

h3.fs30.ffa.mb20 How can I help?

.fs18.lh130.mb30
  ol.ol
    li.mb5 The project requires for testing. It would be great if you check a functionality of a user's profile and create an issue on github if you find a problem. Just try sign up / login. Try to connect your profile to social networks, update your password and so on. Any new issue on github helps.
    li.mb5 Stars and forks on github are welcome always. Don't hesitate to provide some moral support. It's really important for any open source initiative. Thanks!
    li.mb5 If you find any typo or grammar mistake, if you can improve some copies of docs, please, let me know. Issues on github are welcome.